### PR TITLE
Fix Markdown formatting

### PR DESCRIPTION
**Pull request by cwestwater**
### Changed
- Fixed spacing around **Description** in all DSC Resources Documentation.

### CODE REVIEW

**Comment by SimeonGerginov** [comment]
```
git filter-branch --msg-filter "cat - && echo && echo 'Signed-off-by: Your Name <Your.Name@example.com>'" HEAD~3..HEAD
git push origin <Your Branch Name> --force
```

**Comment by cwestwater** [comment]
I have performed the step above Simon. Apologies I am a Git newbie!

**Comment by SimeonGerginov** [comment]
No problem! One small thing you missed is the ```<``` and ```>``` signs around the email.

You can execute the above command like this and everything should be ok:
```
 git filter-branch --msg-filter "cat - && echo && echo 'Signed-off-by: Colin Westwater <cwestwater@gmail.com>'" HEAD~3..HEAD
 git push origin <Your Branch Name> --force
```

**Comment by cwestwater** [comment]
Done! Thanks Simeon!

**Pull request merged**
